"""Reclaim space from worlds that are history.

Every fork materializes a full checkpoint and every finished world keeps its produced payload,
so a store only ever grows. ``prune`` deletes the payload directories of terminal worlds that
nothing living refers to and marks those worlds ``payload_pruned``. Records, receipts, causal
events, and logs stay: the history is still there, only the bytes that could be regenerated by
re-running the same mission are gone. A pruned world can no longer be inspected, shelled into,
or returned to; anything that needs its payload refuses PAYLOAD_PRUNED by name.

Never pruned: PRIME, the checkpoint ``return`` would go back to (PRIME's parent), any world that
is not terminal, any world with an active job, and any payload directory still referenced by an
unpruned world as its own or base payload, or by a registered root's live generation.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
import os
from pathlib import Path
import shutil
from typing import Any

from . import SCHEMA_VERSION
from .model import utc_now
from .errors import WorldlineError
from .model import World, WorldState
from .paths import WorldlinePaths
from .store import StateStore

_PRUNABLE_STATES = (WorldState.ARCHIVED, WorldState.DEAD, WorldState.DEGRADED, WorldState.COLLAPSED)


def _tree_bytes(path: Path) -> int:
    total = 0
    for current, _directories, files in os.walk(path):
        for name in files:
            try:
                total += os.lstat(os.path.join(current, name)).st_size
            except OSError:
                continue
    return total


def _remove_tree(path: Path) -> None:
    # Payloads are stored read-only; make every directory writable before removal (the top
    # directory included, or unlinking its entries fails with EACCES).
    try:
        os.chmod(path, 0o700)
    except OSError:
        pass
    for current, directories, _files in os.walk(path):
        for name in directories:
            try:
                os.chmod(os.path.join(current, name), 0o700)
            except OSError:
                pass
    shutil.rmtree(path, ignore_errors=False)


class Pruner:
    def __init__(self, paths: WorldlinePaths, store: StateStore) -> None:
        self.paths = paths
        self.store = store

    def plan(self, *, older_than_days: int | None, keep: int | None, logs: bool) -> dict[str, Any]:
        open_transactions = self.store.transactions_in_state(["PREPARED", "AUTHORIZED"])
        if open_transactions:
            raise WorldlineError(
                "PRUNE_BLOCKED",
                "a prepared transaction is open; commit or abort it before pruning",
                {"transactions": [row["transaction_id"] for row in open_transactions]},
            )
        worlds = self.store.worlds()
        prime = self.store.prime()
        protected: set[str] = set()
        if prime is not None:
            protected.add(prime.instance_id)
            if prime.parent_instance:
                protected.add(prime.parent_instance)
        active = {job["world_instance"] for job in self.store.jobs() if job["state"] in ("STARTING", "RUNNING", "FINALIZING")}
        cutoff = None
        if older_than_days is not None:
            cutoff = datetime.now(timezone.utc) - timedelta(days=older_than_days)

        def finished_at(world: World) -> datetime:
            stamp = world.ended or world.born
            return datetime.fromisoformat(stamp.replace("Z", "+00:00"))

        candidates = [
            world for world in worlds
            if world.state in _PRUNABLE_STATES
            and not world.payload_pruned
            and world.instance_id not in protected
            and world.instance_id not in active
            and (cutoff is None or finished_at(world) < cutoff)
        ]
        candidates.sort(key=finished_at)
        if keep is not None and keep > 0:
            candidates = candidates[: max(0, len(candidates) - keep)]
        pruning = {world.instance_id for world in candidates}

        referenced: set[str] = set()
        for world in worlds:
            if world.instance_id in pruning:
                continue
            for reference in (world.payload_path, world.base_payload_path):
                referenced.add(os.path.realpath(reference))
        for root in self.store.roots():
            try:
                live = os.path.realpath(bytes(root["path"]))
            except OSError:
                continue
            referenced.add(os.fsdecode(os.path.dirname(live)))

        directories: dict[str, dict[str, Any]] = {}
        entries: list[dict[str, Any]] = []
        for world in candidates:
            own: list[str] = []
            for reference in (world.payload_path, world.base_payload_path):
                real = os.path.realpath(reference)
                if real in referenced or real in directories or not os.path.isdir(real):
                    continue
                directories[real] = {"path": real, "bytes": _tree_bytes(Path(real)), "world": world.alias}
                own.append(real)
            overlay = self.paths.overlays / world.instance_id
            if overlay.is_dir():
                real = os.path.realpath(overlay)
                if real not in directories:
                    directories[real] = {"path": real, "bytes": _tree_bytes(overlay), "world": world.alias}
                    own.append(real)
            log_files: list[str] = []
            if logs:
                for candidate in self.paths.logs.glob(f"{world.instance_id}.*"):
                    log_files.append(str(candidate))
            if not own and not log_files:
                # Everything this world points at is still someone else's (a shared checkpoint):
                # nothing to reclaim, so it is left untouched and stays returnable.
                continue
            entries.append({
                "alias": world.alias,
                "instanceId": world.instance_id,
                "state": world.state.value,
                "finished": world.ended or world.born,
                "directories": own,
                "logs": log_files,
                "bytes": sum(directories[item]["bytes"] for item in own),
            })
        return {
            "worlds": entries,
            "directories": sorted(directories.values(), key=lambda item: item["path"]),
            "bytes": sum(item["bytes"] for item in directories.values()),
            "protected": sorted(protected),
            "criteria": {"olderThanDays": older_than_days, "keep": keep, "logs": logs},
        }

    def apply(self, plan: dict[str, Any]) -> dict[str, Any]:
        removed_bytes = 0
        removed_directories: list[str] = []
        pruned: list[str] = []
        failures: list[dict[str, str]] = []
        for entry in plan["worlds"]:
            world = self.store.world(entry["instanceId"])
            for directory in entry["directories"]:
                path = Path(directory)
                if not path.is_dir():
                    continue
                size = _tree_bytes(path)
                try:
                    _remove_tree(path)
                except OSError as exc:
                    failures.append({"path": directory, "error": str(exc)})
                    continue
                removed_bytes += size
                removed_directories.append(directory)
            for log_file in entry["logs"]:
                try:
                    os.unlink(log_file)
                except FileNotFoundError:
                    pass
                except OSError as exc:
                    failures.append({"path": log_file, "error": str(exc)})
            world.payload_pruned = True
            world.pruned_at = utc_now()
            self.store.save_world(world)
            self.store.append_causal_event({
                "schemaVersion": SCHEMA_VERSION,
                "worldInstance": world.instance_id,
                "kind": "prune",
                "actor": "worldline",
                "reason": f"payload pruned: {len(entry['directories'])} directories, {entry['bytes']} bytes",
            })
            pruned.append(world.alias)
        return {
            "pruned": pruned,
            "directories": removed_directories,
            "bytes": removed_bytes,
            "failures": failures,
        }

    def usage(self) -> dict[str, Any]:
        areas = {
            "generations": self.paths.generations,
            "worlds": self.paths.worlds,
            "transactions": self.paths.data / "transactions",
            "overlays": self.paths.overlays,
            "logs": self.paths.logs,
        }
        sizes = {name: (_tree_bytes(path) if path.is_dir() else 0) for name, path in areas.items()}
        return {"bytes": sizes, "total": sum(sizes.values())}


def require_payload(world: World) -> None:
    if world.payload_pruned:
        raise WorldlineError(
            "PAYLOAD_PRUNED",
            f"world {world.alias} was pruned on {world.pruned_at}; its payload no longer exists",
            {"world": world.alias, "prunedAt": world.pruned_at},
        )
